# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSID', models.IntegerField(null=True)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('img', models.CharField(default=b'', max_length=100)),
                ('desc', models.CharField(default=b'', max_length=700)),
                ('cat', models.CharField(default=b'', max_length=20)),
                ('origin', models.CharField(default=b'', max_length=20)),
                ('classi', models.CharField(default=b'', max_length=50)),
                ('region', models.CharField(default=b'', max_length=50)),
                ('prodtype', models.CharField(default=b'', max_length=50)),
                ('ABV', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('style1', models.CharField(default=b'', max_length=50)),
                ('package', models.CharField(default=b'', max_length=20)),
                ('style2', models.CharField(default=b'', max_length=50)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('UOM', models.CharField(default=b'', max_length=10)),
                ('age', models.CharField(default=b'', max_length=10)),
                ('container', models.CharField(default=b'', max_length=20)),
                ('brand', models.CharField(default=b'', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retail', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('QOH', models.IntegerField(default=0)),
                ('PPU', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('invstmt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dPrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dPPU', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
